//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eproject_Online_floral_delivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public long cartID { get; set; }
        public Nullable<long> productID { get; set; }
        public string image { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> districtID { get; set; }
        public Nullable<long> wardID { get; set; }
        public string address { get; set; }
        public Nullable<long> customerID { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string fullname { get; set; }
        public string phone { get; set; }
        public Nullable<long> messageID { get; set; }
        public string note { get; set; }
    }
}
